<template>
  <div class="card mb-3">
    <div class="card-body" style="padding: 1.6rem">
      <div>
        <div class="d-flex mb-3">
          <h1 class="m-0">
            <!-- <Icon class="me-2" style="transform: translateY(-2px)">CloudRain</Icon> -->
            Cloud Backups
          </h1>
        </div>
      </div>
      <p>
        All data generated by this application, including your user information, library, settings,
        and game progress, is first stored locally in your browser.
      </p>

      <p class="mb-1">
        To share your data between devices, you can use cloud backups. This allows you to
        synchronize and access your information in multiple devices, ensuring it's always up to
        date.
      </p>
      <!-- <p>
        <a class="link-secondary link-underline-opacity-25 me-3 cursor-pointer">
          How it works
        </a>
        <a class="link-secondary link-underline-opacity-25 me-2 cursor-pointer">
          Why is there a quota?
        </a>
      </p> -->
    </div>
    <div class="card-footer">
      <div class="row align-items-center">
        <div class="col-auto">
          <label class="form-check form-switch m-0">
            <input
              v-model="$auth.config.cloud"
              class="form-check-input position-static"
              type="checkbox"
              @change="setConfig('cloud')" />
            <span class="form-check-label form-check-label-on">Cloud Backups are enabled</span>
            <span class="form-check-label form-check-label-off">Cloud Backups are disabled</span>
          </label>
        </div>
      </div>
    </div>
  </div>

  <!-- <pre>
    $Backup {{ $backup }}
    $Cloud {{ $cloud }}
    Conf {{ $auth.config }}
  </pre> -->

  <div v-if="$auth.config.cloud && $backup.is !== 'local'" class="card mb-3">
    <div class="card-body">
      <h2 id="settings" class="mb-3">Backup settings</h2>
      <!-- <p class="card-subtitle">Adjust your preferences</p> -->

      <div class="row">
        <div class="col-md-12 nope-col-lg-8">
          <div class="mb-3 pb-2">
            <div class="form-label">Conflict tolerance</div>
            <div class="text-muted">
              A conflict occurs when there are backups from different devices. Conflict tolerance
              allows you to decide how to resolve conflicts, enabling the application to
              automatically handle them.
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <label class="form-check form-switch cursor-pointer pb-2">
                <input
                  v-model="$auth.config.cloud_resolve"
                  type="checkbox"
                  class="form-check-input"
                  @change="setConfig('cloud_resolve')" />
                <span class="form-check-label form-label">Automatic conflict resolution</span>

                <span class="form-check-description">
                  When enabled, conflicts in synchronization conflicts will be resolved based on the
                  version tolerance and action.
                </span>
              </label>
            </div>
            <div class="col-2">
              <div class="form-label">Tolerance</div>
              <!-- <h4 class="card-title mb-2">Username2</h4> -->
              <v-text-field
                v-model.number="$auth.config.cloud_tolerance"
                density="comfortable"
                type="number"
                @blur="setConfig('cloud_tolerance')" />
            </div>
            <div class="col-4">
              <label class="form-label">Action on conflict</label>
              <v-select
                v-model="$auth.config.cloud_action"
                :items="[
                  { value: 'downloadIfNewer', title: 'Download if cloud is newer' },
                  { value: 'downloadAlways', title: 'Always download' },
                ]"
                item-title="title"
                item-value="value"
                @update:model-value="setConfig('cloud_action')" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div v-if="false && $auth.config.cloud && $backup.is !== 'local'" class="card mb-3">
    <div class="card-body">
      <h2 id="status" class="mb-3">Synchronization status</h2>

      <template>
        <h4 class="mb-1">Local-only database</h4>
        <p>
          Your data is stored directly in your browser's IndexedDB and is not synced to the cloud.
          This means it is only accessible on this device and by you.
          <!-- All your data lives directly in your browser's indexedDB and not in the
            cloud, so it is only accesible to you. -->
        </p>
      </template>

      <div class="row g-3">
        <div v-if="$backup.is == 'syncing'" class="d-flex align-items-center">
          <div class="avatar avatar-sm rounded-circle bg-green-lt" style="--tblr-bg-opacity: 0.3">
            <Icon size="18" width="1.5">CloudRain</Icon>
          </div>
          <div class="ms-3">
            <span class="text-body">Synchronizing...</span>
          </div>
        </div>

        <div v-if="$backup.is == 'sync:done'" class="d-flex align-items-center">
          <div class="avatar avatar-sm rounded-circle bg-green-lt" style="--tblr-bg-opacity: 0.3">
            <Icon size="18" width="1.5">CloudCheck</Icon>
          </div>
          <div class="ms-3">
            <span class="text-body">Connected and synchronized</span>
            <div class="text-secondary">
              Last backup
              {{ dates.dynamicTimeAgo($auth.cloud.updated_at) }} ago
            </div>
          </div>
        </div>

        <!-- <div class="col-md-12 nope-col-lg-8">
          <div class="form-check-description ms-1" style="vertical-align: top">
            <Icon
              size="14"
              width="1.5"
              class="tabler-icon tabler-icon-click mt-1 me-2"
              style="vertical-align: top">
              Click
            </Icon>
            <div class="d-inline-block">
              To change the states shown in the sidebar menu
              <br />
              go to the
              <NuxtLink to="/account/states">states configuration page</NuxtLink>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>

  <div v-if="$backup.is == 'local'" class="card mb-3">
    <div class="card-body">
      <h2 class="mb-2">Enable cloud saves</h2>
      <p class="card-subtitle">Enable cloud sync by logging in</p>
      <p>
        In order to enable cloud sync, you need to login with your Steam account.
        <br />
        This is a safe process, and only your SteamID will be shared with us.
      </p>
      <a class="btn btn-github" href="https://api.backlog.rip/auth/steam">
        <Icon class="me-2">BrandSteam</Icon>
        Sign in with Steam
      </a>
    </div>
  </div>

  <div v-if="$auth.config.cloud" class="card mb-3">
    <div class="card-body">
      <h2 id="quota" class="card-title mb-2">Cloud usage and quota</h2>
      <!-- <p class="card-subtitle">Amount of data stored in the cloud.</p> -->
      <div class="row">
        <div class="col-12">
          <div class="form-label">How backups work</div>
          <div class="text-muted">
            <p>
              Backups are automatic snapshots of your data that are stored in the cloud. They allow
              you to restore your data in case of loss or when switching devices.
            </p>
            <p>
              For storage reasons, you can keep up to 3 backups in the cloud. Each backup contains
              all your data: games, states and account settings.
            </p>
          </div>
        </div>
      </div>
    </div>
    <table class="table card-table table-vcenter">
      <thead>
        <tr>
          <th class="text-right" style="width: 25%">Dimension</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text-right">Account and settings</td>
          <!-- <td>
            <small>
              <span class="badge bg-success me-1"></span>
              Synced
            </small>
          </td> -->
          <td class="text-secondary">
            Your account information and application settings are also backed up.
          </td>
        </tr>
        <tr>
          <td class="text-right">Games</td>
          <!-- <td>
            {{ $backup.games || 0 }}
            <small class="text-muted me-3">/ ∞</small>

            <tippy
              :allow-h-t-m-l="true"
              class="text-muted ms-auto cursor-help"
              content="<p>The amount of games in your library. This includes favorites and hidden games. </p>
              <p>Currently, there is no limit on the number of backed-up games, but future
              limits may apply based on server resources.</p>">
              <span class="form-help">?</span>
            </tippy>
          </td> -->
          <td class="text-secondary">
            All your games are included in the backup. Custom states, playtime and other data are
            also saved.
          </td>
        </tr>

        <tr>
          <td class="text-right">States</td>
          <!-- <td>
            {{ $cloud.backup.states || 0 }}
            <small class="text-muted me-3">/ ∞</small>

            <tippy
              :allow-h-t-m-l="true"
              class="text-muted ms-auto cursor-help"
              content="Currently, there is no limit on the number of backed-up lists, but future limits may apply based on server resources.">
              <span class="form-help">?</span>
            </tippy>
          </td> -->
          <td class="text-secondary">
            All your states are included in the backup. This includes custom states you have
            created.
          </td>
        </tr>

        <tr>
          <td class="text-right">Lists</td>
          <!-- <td>
          </td> -->
          <td class="text-secondary">
            <!-- <div class="progress progress">
              <div class="progress-bar bg-primary" style="width: 24.9%"></div>
            </div> -->
            <small class="text-secondary">
              <Icon size="14">Rotate2</Icon>
              This synchronization is planned for a future update
            </small>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title mb-2">Synchronization history</h2>
      <p class="card-subtitle">Your latest backups</p>
    </div>
    <table class="table card-table table-vcenter">
      <thead>
        <tr>
          <th>Version</th>
          <th>Hash</th>
          <th>Date</th>
          <th>Account</th>
          <th>Games</th>
          <th>States</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <template v-for="(backup, i) in backups" :key="i">
          <tr>
            <td>
              <code class="text-muted me-2">v{{ backup.hash.split('.')[0] }}</code>
              <small v-if="$auth.cloud.hash == backup.hash" class="label">
                <span class="badge bg-success mx-1"></span>
                Active
              </small>
            </td>
            <td>
              <kbd class="text-muted text-uppercase">
                {{ backup.hash.includes('.') ? backup.hash.split('.')[1] : backup.hash }}
              </kbd>
            </td>
            <td>
              <small class="text-muted">
                {{
                  dates.dynamicTimeAgo(
                    $auth.cloud.hash == backup.hash ? $auth.cloud.updated_at : backup.updated_at
                  )
                }}
                ago ~
                {{
                  $moment(
                    $auth.cloud.hash == backup.hash ? $auth.cloud.updated_at : backup.updated_at
                  ).format('LLL')
                }}
              </small>
            </td>
            <td><span class="badge bg-success mx-1"></span></td>
            <td>
              <small class="text-muted">
                {{ backup.games || 0 }}
              </small>
            </td>
            <td>
              <small class="text-muted">
                {{ backup.states || 0 }}
              </small>
            </td>
            <td class="text-end">
              <div class="btn-action" v-tippy="'Restore this backup'" @click="applyBackup(backup)">
                <Icon size="14">CloudDownload</Icon>
              </div>
            </td>
          </tr>
        </template>
      </tbody>
    </table>
  </div>
</template>

<script>
/**
 * @file:    \pages\account\sections\cloud.vue
 * @desc:    ...
 * ----------------------------------------------
 * Created Date: 15th August 2024
 * Modified: 6th November 2025 - 01:07:50
 **/

export default {
  name: 'AccountCloudSync',

  data() {
    return {}
  },

  computed: {
    ...mapStores(useBackupStore),
    ...mapState(useBackupStore, ['backups']),

    $backup() {
      return this.$cloud?.backup || {}
    },
  },

  methods: {
    //+-------------------------------------------------
    // setConfig()
    // Updates a field in the db via $auth
    // -----
    // Created on Mon Dec 18 2023
    //+-------------------------------------------------
    async setConfig(field) {
      this.$auth.setConfig(field)
      this.$toast.success('Your preferences have been saved')

      // Todo: reconnect using another method
      // await delay(333)
      // this.backupStore.connect()
    },

    //+-------------------------------------------------
    // applyBackup()
    // -----
    // Created on Tue Apr 01 2025
    //+-------------------------------------------------
    async applyBackup(backup) {
      // this.$refs.restore.show(backup)
      this.$mitt.emit('backup:restore', { backup })
    },

    async init() {},
  },

  mounted() {
    this.init()
  },
}
</script>
