<template>
  <div class="card mb-3">
    <div class="card-body" style="padding: 1.6rem">
      <div>
        <div class="d-flex mb-3">
          <h1 class="m-0">Cloud Sync</h1>
        </div>
      </div>
      <p>
        All data generated by this application, including your user information, library,
        settings, and game progress, is stored locally in your browser.

        <!-- All the data generated by this application, as well as your userdata, including
        your library, configuration, and game states, is stored locally in your browser. -->
      </p>

      <p class="mb-1">
        To access your data from any device, you can use the cloud sync feature. This
        allows you to synchronize and access your information across multiple devices,
        ensuring it's always up to date.
        <!-- To access your data from any location, you can utilize the cloud sync feature.
        This enables you to access your data on any device and synchronize it with the
        cloud. -->
      </p>
      <!-- <p>
        <a class="link-secondary link-underline-opacity-25 me-3 cursor-pointer">
          How it works
        </a>
        <a class="link-secondary link-underline-opacity-25 me-2 cursor-pointer">
          Why is there a quota?
        </a>
      </p> -->
    </div>
    <div v-if="$cloud.is !== 'local'" class="card-footer">
      <div class="row align-items-center">
        <div class="col-auto">
          <label class="form-check form-switch m-0">
            <input
              v-model="$auth.config.cloud"
              class="form-check-input position-static"
              type="checkbox"
              @change="setConfig('cloud')" />
            <span class="form-check-label form-check-label-on">
              Cloud Sync is enabled
            </span>
            <span class="form-check-label form-check-label-off">
              Cloud Sync is disabled
            </span>
          </label>
        </div>
      </div>
    </div>
  </div>

  <div v-if="$auth.config.cloud && $cloud.is !== 'local'" class="card mb-3">
    <div class="card-body">
      <h2 id="settings" class="mb-3">Cloud settings</h2>
      <!-- <p class="card-subtitle">Adjust your preferences</p> -->

      <div class="row">
        <div class="col-md-12 nope-col-lg-8">
          <div class="mb-3 pb-2">
            <div class="form-label">Conflict tolerance</div>
            <div class="text-muted">
              A conflict occurs when there are backups from different devices. Conflict
              tolerance allows you to decide how to resolve conflicts, enabling the
              application to automatically handle them.
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <label class="form-check form-switch cursor-pointer pb-2">
                <input
                  v-model="$auth.config.cloud_resolve"
                  type="checkbox"
                  class="form-check-input"
                  @change="setConfig('cloud_resolve')" />
                <span class="form-check-label form-label">
                  <Icon
                    size="14"
                    width="1.3"
                    class="me-1"
                    style="transform: translateY(-2px)">
                    CloudExclamation
                  </Icon>
                  Automatic conflict resolution
                </span>

                <span class="form-check-description">
                  When enabled, conflicts in synchronization conflicts will be resolved
                  based on the version tolerance and action.
                </span>
              </label>
            </div>
            <div class="col-2">
              <div class="form-label">Tolerance</div>
              <!-- <h4 class="card-title mb-2">Username2</h4> -->
              <v-text-field
                v-model.number="$auth.config.cloud_tolerance"
                density="comfortable"
                type="number"
                @blur="setConfig('cloud_tolerance')" />
            </div>
            <div class="col-4">
              <label class="form-label">Action on conflict</label>
              <v-select
                v-model="$auth.config.cloud_action"
                :items="[
                  { value: 'downloadIfNewer', title: 'Download if cloud is newer' },
                  { value: 'downloadAlways', title: 'Always download' },
                  { value: 'uploadAlways', title: 'Always upload' },
                ]"
                item-title="title"
                item-value="value"
                @update:model-value="setConfig('cloud_action')" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div v-if="$auth.config.cloud && $cloud.is !== 'local'" class="card mb-3">
    <div class="card-body">
      <h2 id="status" class="mb-3">Synchronization status</h2>
      <!-- <p class="card-subtitle">Your data is backed up in the cloud</p> -->

      <template>
        <h4 class="mb-1">Local-only database</h4>
        <p>
          Your data is stored directly in your browser's IndexedDB and is not synced to
          the cloud. This means it is only accessible on this device and by you.
          <!-- All your data lives directly in your browser's indexedDB and not in the
            cloud, so it is only accesible to you. -->
        </p>
      </template>

      <div class="row g-3">
        <div v-if="$cloud.is == 'syncing'" class="d-flex align-items-center">
          <div
            class="avatar avatar-sm rounded-circle bg-green-lt"
            style="--tblr-bg-opacity: 0.3">
            <Icon size="18" width="1.5">CloudRain</Icon>
          </div>
          <div class="ms-3">
            <span class="text-body">Synchronizing...</span>
          </div>
        </div>

        <div v-if="$cloud.is == 'sync:done'" class="d-flex align-items-center">
          <div
            class="avatar avatar-sm rounded-circle bg-green-lt"
            style="--tblr-bg-opacity: 0.3">
            <Icon size="18" width="1.5">CloudCheck</Icon>
          </div>
          <div class="ms-3">
            <span class="text-body">Connected and synchronized</span>
            <div class="text-secondary">
              Last backup
              {{ dates.dynamicTimeAgo($auth.cloud.updated_at) }} ago
            </div>
          </div>
        </div>

        <!-- <div class="col-md-12 nope-col-lg-8">
          <div class="form-check-description ms-1" style="vertical-align: top">
            <Icon
              size="14"
              width="1.5"
              class="tabler-icon tabler-icon-click mt-1 me-2"
              style="vertical-align: top">
              Click
            </Icon>
            <div class="d-inline-block">
              To change the states shown in the sidebar menu
              <br />
              go to the
              <NuxtLink to="/account/states">states configuration page</NuxtLink>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>

  <div v-if="$cloud.is == 'local'" class="card mb-3">
    <div class="card-body">
      <h2 class="mb-2">Enable cloud saves</h2>
      <p class="card-subtitle">Enable cloud sync by logging in</p>
      <p>
        In order to enable cloud sync, you need to login with your Steam account.
        <br />
        This is a safe process, and only your SteamID will be shared with us.
      </p>
      <a class="btn btn-github" href="https://api.backlog.rip/auth/steam">
        <Icon class="me-2">BrandSteam</Icon>
        Sign in with Steam
      </a>
    </div>
  </div>

  <div v-if="$auth.config.cloud && $cloud.is == 'sync:done'" class="card mb-3">
    <div class="card-body">
      <h2 id="quota" class="card-title mb-2">Cloud usage and quota</h2>
      <p class="card-subtitle">Amount of data stored in the cloud.</p>
    </div>
    <table class="table card-table table-vcenter">
      <thead>
        <tr>
          <th>Dimension</th>
          <th colspan="2">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Games</td>
          <td>
            {{ $cloud.backup.games || 0 }}
            <small class="text-muted me-3">/ ∞</small>

            <tippy
              :allow-h-t-m-l="true"
              class="text-muted ms-auto cursor-help"
              content="<p>The amount of games in your library. This includes favorites and hidden games. </p>
              <p>Currently, there is no limit on the number of backed-up games, but future
              limits may apply based on server resources.</p>">
              <span class="form-help">?</span>
            </tippy>
          </td>
          <td class="w-50">
            <div class="progress progress">
              <div
                class="progress-bar"
                :class="{
                  'bg-primary': $cloud.backup.games < 3000,
                  'bg-red': $cloud.backup.games >= 3000,
                }"
                :style="`width: ${($cloud.backup.games / 3000) * 100}%`"></div>
            </div>
          </td>
        </tr>

        <tr>
          <td>States</td>
          <td>
            {{ $cloud.backup.states || 0 }}
            <small class="text-muted me-3">/ ∞</small>

            <tippy
              :allow-h-t-m-l="true"
              class="text-muted ms-auto cursor-help"
              content="Currently, there is no limit on the number of backed-up lists, but future limits may apply based on server resources.">
              <span class="form-help">?</span>
            </tippy>
          </td>
          <td class="w-50">
            <div class="progress progress">
              <div
                class="progress-bar bg-primary"
                :style="`width: ${($cloud.backup.states / 100) * 100}%`"></div>
            </div>
          </td>
        </tr>

        <tr>
          <td>Account and settings</td>
          <td>
            <small>
              <span class="badge bg-success me-1"></span>
              Synced
            </small>
          </td>
          <td class="w-50">
            <div class="progress progress">
              <div class="progress-bar bg-green" style="width: 100%"></div>
            </div>
          </td>
        </tr>

        <tr>
          <td>Lists</td>
          <td>
            <!-- {{ $cloud.backup.games || 0 }}
            <small class="text-muted">/ 25</small> -->
          </td>
          <td class="w-50">
            <!-- <div class="progress progress">
              <div class="progress-bar bg-primary" style="width: 24.9%"></div>
            </div> -->
            <small class="text-secondary">
              <Icon size="14">Rotate2</Icon>
              This synchronization is planned for a future update
            </small>
          </td>
        </tr>

        <tr>
          <td>Journal</td>
          <td>
            <!-- {{ $cloud.backup.games || 0 }}
            <small class="text-muted">/ 10</small> -->
          </td>
          <td class="w-50">
            <!-- <div class="progress progress">
              <div class="progress-bar bg-primary" style="width: 35.96%"></div>
            </div> -->
            <small class="text-secondary">
              <Icon size="14">Rotate2</Icon>
              This synchronization is planned for a future update
            </small>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div v-if="$auth.config.cloud && $cloud.is == 'sync:done'" class="card mb-3">
    <div class="card-body">
      <h2 class="card-title mb-2">Synchronization history</h2>
      <p class="card-subtitle">Your latest backups</p>
    </div>
    <table class="table card-table table-vcenter">
      <thead>
        <tr>
          <th>Version</th>
          <th>Hash</th>
          <th>Date</th>
          <th>Account</th>
          <th>Games</th>
          <th>States</th>
          <!-- <th></th> -->
        </tr>
      </thead>
      <tbody>
        <template v-for="(backup, i) in $cloud.backups" :key="i">
          <tr>
            <td>
              <code class="text-muted me-2">v{{ backup.hash.split('.')[0] }}</code>
              <small v-if="$auth.cloud.hash == backup.hash" class="label">
                <span class="badge bg-success mx-1"></span>
                Active
              </small>
            </td>
            <td>
              <kbd class="text-muted text-uppercase">
                {{ backup.hash.includes('.') ? backup.hash.split('.')[1] : backup.hash }}
              </kbd>
            </td>
            <td>
              <small class="text-muted">
                {{
                  dates.dynamicTimeAgo(
                    $auth.cloud.hash == backup.hash
                      ? $auth.cloud.updated_at
                      : backup.updated_at
                  )
                }}
                ago ~
                {{
                  $moment(
                    $auth.cloud.hash == backup.hash
                      ? $auth.cloud.updated_at
                      : backup.updated_at
                  ).format('LLL')
                }}
              </small>
            </td>
            <td><span class="badge bg-success mx-1"></span></td>
            <td>
              <small class="text-muted">
                {{
                  $auth.cloud.hash == backup.hash
                    ? $cloud.backup.games
                    : backup.games || 0
                }}
              </small>
            </td>
            <td>
              <small class="text-muted">
                {{
                  $auth.cloud.hash == backup.hash
                    ? $cloud.backup.states || 0
                    : backup.states || 0
                }}
              </small>
            </td>
            <!-- <td class="text-end">
              <div class="btn-action">
                <Icon>CloudDownload</Icon>
              </div>
            </td> -->
          </tr>
        </template>
      </tbody>
    </table>
  </div>
</template>

<script>
/**
 * @file:    \pages\account\sections\cloud.vue
 * @desc:    ...
 * ----------------------------------------------
 * Created Date: 15th August 2024
 * Modified: Thu 13 March 2025 - 15:02:12
 **/

export default {
  name: 'AccountCloudSync',

  data() {
    return {}
  },

  computed: {
    ...mapStores(useCloudStore),
  },

  methods: {
    //+-------------------------------------------------
    // setConfig()
    // Updates a field in the db via $auth
    // -----
    // Created on Mon Dec 18 2023
    //+-------------------------------------------------
    async setConfig(field) {
      this.$auth.setConfig(field)
      this.$toast.success('Your preferences have been saved')
      await delay(333)

      this.cloudStore.connect()
    },

    async init() {},
  },

  mounted() {
    this.init()
  },
}
</script>
